### ISSUE TITLE
RT-890-SPI-Restore-CLI source code

### ISSUE THREAD

**Issue by 8de2fdb0** [OEFW-community/RT-890-custom-firmware#123]
Is there source code for the exe file in https://github.com/OEFW-community/RT-890-SPI-Restore-CLI available?

And in what sense is that cli different to https://github.com/OEFW-community/radtel-rt-890-flasher-cli 

Also I am wondering how is the custom firmware flashed over the custom firmware, the command on all the flash utils seems `x57` 
As for example seen in the python tool
 ```
     CMD_ERASE_FLASH = 0x39
    CMD_READ_FLASH = 0x52
    CMD_WRITE_FLASH = 0x57
   ``` 
   
   But looking @ `HandlerUSART1` which looks like the uart interupt handler I can't find `0x57`, is there a bootloader that handles that ?

**Comment by reppad** [comment]
> Is there source code for the exe file in https://github.com/OEFW-community/RT-890-SPI-Restore-CLI available?

Unfortunately this piece of software was not open sourced by its original developer.

> And in what sense is that cli different to https://github.com/OEFW-community/radtel-rt-890-flasher-cli

`radtel-rt-890-flasher-cli` is a CLI tool to flash firmwares (the software of the radio) on the MCU flash (like https://github.com/OEFW-community/radtel-rt-890-flasher).
`RT-890-SPI-Restore-CLI` is a CLI tool to restore external SPI flash datas (configuration, channels, calibrations...).

> Also I am wondering how is the custom firmware flashed over the custom firmware, the command on all the flash utils seems `x57` As for example seen in the python tool
> 
> ```
>     CMD_ERASE_FLASH = 0x39
>    CMD_READ_FLASH = 0x52
>    CMD_WRITE_FLASH = 0x57
> ```
> 
> But looking @ `HandlerUSART1` which looks like the uart interupt handler I can't find `0x57`, is there a bootloader that handles that ?

Absolutely, the firmware flashing process rely on the factory bootloader.

**Comment by 8de2fdb0** [comment]
Is there some documentation for the factory bootloader, i think by now I understood that the MCU is from atery, but I can't find any documentation about the bootloader they use and the uart dfu interface.

**Comment by reppad** [comment]
I haven’t had much time to dedicate to this project lately, so some things may have progressed, but as far as I know:

Regarding the 2nd stage bootloader (the one from the radio manufacturer, programmed into the MCU’s flash memory that allows you to choose the radio’s boot mode and flash firmware):
- It is not documented by the manufacturer.
- It may have been dumped at the time when the firmware was reverse-engineered, but it has not been published or reverse-engineered itself.

Regarding the bootloader ROM of the MCU AT32F421:
- According to the [documentation](https://www.arterychip.com/download/DS/DS_AT32F421_V2.02_EN.pdf), there is a bootloader that allows programming the MCU via USART1 & 2, but no USB DFU bootloader.
- The MCU’s memory in the radio is locked for reading, so accessing it via the ROM bootloader requires a complete memory wipe, which would brick the radio since we do not have the binary for the 2nd stage bootloader.

So my advice:
It’s safer to stick to using radtel-rt-890-flasher for testing firmwares. It is entirely possible to use it to flash firmwares created from scratch if that’s what you want to do; you just need to use the linker script from this project.

I hope this helps.

**Comment by 8de2fdb0** [comment]
thanks
