### ISSUE TITLE
DCS codes 114 to 466 missing

### ISSUE THREAD

**Issue by traeu** [OEFW-community/RT-890-custom-firmware#71]
My radio came with firmware 1.34. I tried using this OEFW firmware, but after flashing, I was not able to use all DCS codes.
In stock firmware, all DCS codes listed here (https://en.wikipedia.org/wiki/Squelch#DCS) are available, even some more non-standard ones.
On OEFW firmware, there are DCS codes available starting with 0, 5 and 6. I am not able to select DCS codes between 114 and 466.
Also, the scroll direction is wrong in DCS menu, pressing the arrow down key increases the DCS code, but thats only a small unimportant issue.

**Comment by ea7hjb** [comment]
Ok, I checked this and the DCS code list needs a little love, because is a mess (the CTCSS is fine and complete). This is what I found: on original firmware 1.34 CTCSS/DCS are OK, none missing, none non-standard in the list. The OEFW has the list badly sorted, with repeated codes, missing ones, and non-standard one addeds (will attach the list at the end). OEFW-community has inherit this (perhaps this is why frequency scanner doesn't work well with DCS codes?)

What would I do (if I had enought brain)?¿: leave only standard codes and remove all non-standard ones. Then, in a future, add the posibility to manually enter thru the keyboard any non-standard code you desire. And yes, I checked this and works fine if you program any CTCSS between 60.0-299.9Hz and any DCS between 000 and 777 with the CPS. The Radtel will transmit and receive perfectly fine custom subtones, tested vs a professional Vertex Standard equipment, so perhaps this would be a nice touch and not difficult to implement.

Ok, here comes the current list:

023 (Standard)
025 (Standard)
026 (Standard)
031 (Standard)
032 (Standard)
036 (Standard)
043 (Standard)
047 (Standard)
051 (Standard)
053 (Standard)
054 (Standard)
065 (Standard)
071 (Standard)
072 (Standard)
073 (Standard)
074 (Standard)
514 (Non-standard)
515 (Non-standard)
516 (Standard)
522 (Non-standard)
525 (Non-standard)
531 (Non-standard)
532 (Standard)
534 (Non-standard)
543 (Non-standard)
545 (Non-standard)
552 (Non-standard)
555 (Non-standard)
556 (Non-standard)
562 (Non-standard)
565 (Standard)
572 (Non-standard)
574 (Non-standard)
605 (Non-standard)
612 (Standard)
623 (Non-standard)
625 (Non-standard)
626 (Non-standard)
643 (Non-standard)
644 (Non-standard)
645 (Non-standard)
646 (Non-standard)
651 (Non-standard)
652 (Non-standard)
655 (Non-standard)
661 (Non-standard)
663 (Non-standard)
665 (Non-standard)
666 (Non-standard)
671 (Non-standard)
674 (Non-standard)
706 (Non-standard)
711 (Non-standard)
715 (Non-standard)
725 (Non-standard)
731 (Standard)
732 (Standard)
743 (Standard)
746 (Non-standard)
751 (Non-standard)
756 (Non-standard)
764 (Non-standard)
765 (Non-standard)
771 (Non-standard)
011 (Non-standard)
012 (Non-standard)
013 (Non-standard)
023 (Standard) REPEATED
031 (Standard) REPEATED
032 (Standard) REPEATED
045 (Non-standard)
046 (Non-standard)
052 (Non-standard)
054 (Standard) REPEATED
055 (Non-standard)
062 (Non-standard)
064 (Non-standard)
065 (Standard) REPEATED
066 (Non-standard)
503 (Standard)
506 (Standard)
516 (Standard) REPEATED
523 (Standard)
526 (Standard)
532 (Standard) REPEATED
546 (Standard)
565 (Standard)
606 (Standard)
612 (Standard) REPEATED
624 (Standard)
627 (Standard)
631 (Standard)
632 (Standard)
645 (Non-standard)
654 (Standard)
662 (Standard)
664 (Standard)
703 (Standard)
712 (Standard)
723 (Standard)
731 (Standard) REPEATED
732 (Standard) REPEATED
734 (Non-standard)
743 (Standard) REPEATED
754 (Standard)

And the missing standard DCS codes:
114
115
116
122
125
131
132
134
143
145
152
155
156
162
165
172
174
205
212
223
225
226
243
244
245
246
251
252
255
261
263
265
266
271
274
306
311
315
325
331
332
343
346
351
356
364
365
371
411
412
413
423
431
432
435
445
446
452
454
455
462
464
465
466

How can I be of help?

**Comment by traeu** [comment]
I came to the conclusion that official firmware 1.34 has some non-standard codes because I compared it to wikipedia's list. Some codes that you listed as standard are not in the table of wikipedia. I don't know much about DCS, maybe wikipedia's list is incomplete... So my information may be wrong about this (but it's not really relevant anyway...)

**Comment by ea7hjb** [comment]
> I came to the conclusion that official firmware 1.34 has some non-standard codes because I compared it to wikipedia's list. Some codes that you listed as standard are not in the table of wikipedia. I don't know much about DCS, maybe wikipedia's list is incomplete... So my information may be wrong about this (but it's not really relevant anyway...)

Codes 036, 053, 122, 145, 212, 225, 246, 252, 255, 266, 274, 325, 332, 356, 435, 446, 452, 454, 455, 462, 523 and 526 are strictly non standard (ETSI TS 103 236), but widely accepted and have been included in a lot of devices over the years (Yaesus, Icoms, Kenwood, etc...), so they are worth to be added.

Same happens with CTCSS 159.8, 165.5, 171.3, 177.3, 183.5, 189.9, 196.6, 199.5, 206.5, 229.1 and 254.1. Also, with 213.8, 221.3, 237.1 and 245.5, but those last four are more uncommon to see.

P.S.: Another valid source to take a proper list for refence would be to copy the codes from the availables in the original CPS, which match 1:1 the 1.34 firmware. Despite custom codes 60-299.9Hz and 000-777 can be manually typed, as I said previously.

**Comment by xawen** [comment]
This should be resolved.  Thank you for the very detailed report.
